spring:
  datasource:
    username: root
    password: Aa773949603
    url: jdbc:mysql://47.94.197.32:3306/cojo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true


---
spring:
  data:
    redis:
      host: 47.94.197.32
      port: 6379
      password: Aa773949603